version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ddlabs
      MYSQL_USER: test
      MYSQL_PASSWORD: toor
      MYSQL_PORT: 3306
      MYSQL_HOST: db 
    container_name: ddlabs-db
    command:
      - --default-authentication-plugin=mysql_native_password
  app1:
    build:
      context: .
    volumes:
      - .:/go/src/app:rw
    restart: always
    ports:
      - "8080:8088"
    container_name: dd-goapp
    
  app2:

